### PR TITLE
resizes images in use to max display size (up to 4K screen) and optimizes them

### PR DESCRIPTION
**Pull request by juliencarnot**
to make that homepage fast!

### CODE REVIEW

**Comment by juliencarnot** [comment]
saves 2,2 Mo of download for displaying the homepage

**Comment by gdpelican** [comment]
@robguthrie I know we talked about supporting 2x retina screens, but these images do seem a bit large even for that; think this is the way to go?

**Comment by robguthrie** [comment]
On my screen the first image is roughly 416 px wide. That means we need to provide 832px for it to look clear on a macbook pro retina screen. The original is 960 so that seems to be about right to me.

Can we optimise them without dropping the resolution?

**Comment by juliencarnot** [comment]
@robguthrie I thought that it was to accommodate Retina in the first place, so I initially [optmized them without resizing](https://github.com/loomio/loomio_org_plugin/commit/6e9b05c34a49b6e442665377baa7c5bfc491bb91), but in all my tests using chromium or firefox with dev console and hiDPI/4K settings, images always display at 416 px wide, not 832.

If we really want to support retina, maybe we need to use responsive images to avoid loading a 3162 KB homepage for all?

**Comment by robguthrie** [comment]
What was the result of optimising without resizing?

**Comment by juliencarnot** [comment]
Optimizing without resizing is already done in 6e9b05c34a49b6e442665377baa7c5bfc491bb91
Original size of 13 images was 3345B, optimization took it to 1019B.

**Comment by robguthrie** [comment]
Arr great. Well we could serve the smaller images if we detect a low res screen, but I'm happy with the 75% gains as they are. If you want to work out how to serve the bigger/smaller images when appropriate that's welcomed. Thanks very much!

**Pull request closed without merging**
